# Generated by Django 4.2.3 on 2023-10-12 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='meta_discription',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='meta_discription',
            new_name='meta_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='small_discription',
            new_name='small_description',
        ),
    ]
